### ISSUE TITLE
Update 'Existing leave requests' after adding a new one

### ISSUE THREAD

**Issue by rooreynolds** [livestax/app-leave-request#1]
As a user, I want to see my new request so I know it's been submitted without having to refresh.

It would be useful, when adding a new request, for the 'Existing leave requests' to update itself to reflect the change. This would give the user some reassuring feedback that their request has been logged.

**Comment by JordanHatch** [comment]
Resolved by 83e89fb.

**Comment by rooreynolds** [comment]
:+1:
